name: CICDassignment
on:
  push:
    branches:
      - 'v[0-9]+.[0-9]+'
  pull_request:
jobs:
  build:
    name: ScanFilesystem
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Trivy vulnerability scanner in repo mode
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          ignore-unfixed: true
          format: 'table'
          output: 'trivy-results.txt'
          exit-code: '1'
          severity: 'CRITICAL'

      - name: SendMsg
        if: failure()
        id: slack
        uses: rtCamp/action-slack-notify@v2
        env:
           SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
           SLACK_TITLE: "Scan failed -YangHan"
           SLACK_MESSAGE: "Failed trivy scan, see uploaded report"

      - name: UploadFile
        if: failure()
        uses: MeilCli/slack-upload-file@v3
        with:
          slack_token: ${{ secrets.SLACK_TOKEN }}
          channel_id: ${{ secrets.SLACK_CHANNELID }}
          file_path: "trivy-results.txt"
          initial_comment: 'post by Yang Han'

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      -
        name: Build and push
        id: build-and-push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: clementiking/cicd-assignment:${{ github.sha}}

      - name: Install cosign
        uses: sigstore/cosign-installer@v3.1.1

      - name: Get data
        id: docker_meta
        uses: docker/metadata-action@v4.4.0
        with:
          images: docker.io/clementiking/cicd-assignment:${{ github.sha}}
          tags: type=sha,format=long      

      - name: Sign image with a key
        run: |
          cosign sign --yes --key env://COSIGN_PRIVATE_KEY  docker.io/clementiking/cicd-assignment:${{ github.sha}}
        env:
          COSIGN_PRIVATE_KEY: ${{ secrets.COSIGN_PRIVATE_KEY }}
          COSIGN_PASSWORD: ${{ secrets.COSIGN_PASSWORD }}
          TAGS: ${{ steps.docker_meta.outputs.tags }}
      
      - name: SendMsg
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_TITLE: Image built and signed
          SLACK_MESSAGE: |
            *Name*: Yang Han
            *Metriculation*: A0287267M
            *Email*:<mailto:e1285213@u.nus.edu|e1285213@u.nus.edu>
            *Git*:<https://github.com/ClementiKing/CICD_assignment.git>
            *Image*: <https://hub.docker.com/repository/docker/clementiking/cicd-assignment/general>